### ISSUE TITLE
npm run start:dev报错了！

### ISSUE THREAD

**Issue by jeremyChenMing** [yvanwangl/AccountSystem#1]
打包完，直接起服务，然后就报错
`npm ERR! missing script: start:dev

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2017-12-22T03_37_12_879Z-debug.log`
请问这个怎么解决啊

**Comment by yvanwangl** [comment]
@jeremyChenMing 报的错误信息是 `missing script: start:dev`，请确保是否是在根目录下运行

**Comment by Thavaprakash** [comment]
Hi Yvanwagl,
It looks great!!, could you give me local mongo database so that i can import and test it.
