### ISSUE TITLE
Local Database needed to import and test

### ISSUE THREAD

**Issue by Thavaprakash** [yvanwangl/AccountSystem#2]
Hi Yvanwagl, 
It looks great !!, could you give me local mongo database so that i can import and test it.

**Comment by yvanwangl** [comment]
@Thavaprakash Of course if you need. But my local database has many dirty data. In my option, you can make some data by yourself, by this way, you can also know about AccountSystem's functions. How do you think ?   :)

**Comment by Thavaprakash** [comment]
Thanks for your prompt reply, Let me try. :)

**Comment by yvanwangl** [comment]
@Thavaprakash You are welcome : )

**Comment by sgrcr** [comment]
# create user
use accountSystem
db.users.insert({'username':'guest','password':'123456','salt':'','admin':'true'})
