### ISSUE TITLE
npm run start:dev 上传商品图片报错

### ISSUE THREAD

**Issue by myronlau** [yvanwangl/AccountSystem#3]
用npm run start:dev 模式运行，测试上传商品图片的时候报错，报错信息：
ENOENT: no such file or directory, stat 'C:\Users\xxxx\Desktop\dev\AccountSystem\dist\index.html'
404

请问是不是因为没有npm run build，所以没生成dist文件夹导致找不到路径？而且现在project里面也没有upload文件夹。

**Comment by yvanwangl** [comment]
@myronlau 应该是缺少 AccountSystem/upload/uploadfiles 目录 及 AccountSystem/service/tmp 目录导致的，你可以自己手动增加这两个目录，或者重新 clone 一下代码，已经增加了这两个目录

**Comment by myronlau** [comment]
@yvanwangl 谢谢这么及时的回复哈，问题解决了。

**Comment by yvanwangl** [comment]
@myronlau 好的，有问题继续交流哈

**Comment by myronlau** [comment]
@yvanwangl 好的，可以方便给下你电邮吗？想跟你请教前端学习和关于这个项目的更多问题。
