### ISSUE TITLE
本地发布模式部署

### ISSUE THREAD

**Issue by myronlau** [yvanwangl/AccountSystem#6]
Hello，我在开发模式时运行项目没有问题，但是以发布模式运行则会报错，可能主要是访问数据库的设置问题。想问下，如果我想把项目以发布模式部署到本地，也是连接本地的数据库，且开机就能运行，需要注意些什么问题呢？

**Comment by yvanwangl** [comment]
@myronlau 就按照部署模式运行就ok的，没有什么特殊处理的地方，注意数据库正常链接
