### ISSUE TITLE
下载后提示 app.model: namespace should be defined

### ISSUE THREAD

**Issue by water-in-stone** [yvanwangl/AccountSystem#8]
按照页面上所有的步骤进行操作，然后得到一个 `app.model: namespace should be defined` 的报错

```
  12 | //app.use({});
  13 | 
  14 | // 3. Model
> 15 | app.model(require('./models/home'));
  16 | app.model(require('./models/orders'));
  17 | /*app.model(require('./models/stocks'));*/
  18 | app.model(require('./models/storage'));
```

**Comment by Eric-Zhong** [comment]
I am try to change the source code as bellow, it seams ok for me.

// 3. Model
app.model(require('./models/home').default);
app.model(require('./models/orders').default);
/*app.model(require('./models/stocks'));*/
app.model(require('./models/storage').default);
/*app.model(require('./models/funds'));*/
app.model(require('./models/manage').default);
app.model(require('./models/systemUser').default);
app.model(require('./models/customers').default);
app.model(require('./models/products').default);
app.model(require('./models/suppliers').default);
app.model(require('./models/settlement').default);
app.model(require('./models/resource').default);
app.model(require('./models/customerBills').default);
app.model(require('./models/supplierBills').default);

**Comment by yvanwangl** [comment]
@water-in-stone @Eric-Zhong 不好意思，这么久没有处理，
这个问题是因为升级 roadhog 2 后配置没有修改导致的，现在已经修复了，可以正常工作 ;)
