### ISSUE TITLE
npm install报错

### ISSUE THREAD

**Issue by USTCLX** [yvanwangl/AccountSystem#9]
<img width="572" alt="default" src="https://user-images.githubusercontent.com/26104564/40614441-6ea3ef9c-62b5-11e8-9ce4-d4bbf2098ee2.png">
你好，clone项目之后，每次npm install都会报错，错误信息如图所示。

**Comment by yvanwangl** [comment]
@USTCLX 
1. 安装前端依赖包 npm install
2. 安装后端依赖包 cd service & npm install
这里需要安装前端依赖包和后端依赖包，是哪一步报错的？
